# Generated by Django 4.1.4 on 2023-08-06 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=1)),
                ('dashboard', models.BooleanField(default=False)),
                ('recurring', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=5000)),
                ('date', models.DateField()),
                ('char1', models.CharField(max_length=5000)),
                ('char2', models.CharField(max_length=5000)),
                ('char3', models.CharField(max_length=5000)),
                ('int1', models.IntegerField(default=1)),
                ('int2', models.IntegerField(default=2)),
                ('int3', models.IntegerField(default=3)),
                ('bool1', models.BooleanField(default=False)),
                ('bool2', models.BooleanField(default=False)),
                ('bool3', models.BooleanField(default=False)),
                ('bool4', models.BooleanField(default=False)),
                ('bool5', models.BooleanField(default=False)),
                ('bool6', models.BooleanField(default=False)),
                ('bool7', models.BooleanField(default=False)),
                ('bool8', models.BooleanField(default=False)),
                ('bool9', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
