# Generated by Django 4.1.4 on 2023-08-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='date',
        ),
    ]
