# Generated by Django 4.1.4 on 2023-08-10 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_daily_date_alter_daily_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('weather', models.CharField(default='', max_length=5000)),
                ('char1', models.CharField(max_length=5000)),
                ('char2', models.CharField(max_length=5000)),
                ('char3', models.CharField(max_length=5000)),
                ('int1', models.IntegerField(default=1)),
                ('int2', models.IntegerField(default=0)),
                ('int3', models.IntegerField(default=0)),
                ('int4', models.IntegerField(default=0)),
                ('int5', models.IntegerField(default=0)),
                ('int6', models.IntegerField(default=0)),
                ('bool1', models.BooleanField(default=False)),
                ('bool2', models.BooleanField(default=False)),
                ('bool3', models.BooleanField(default=False)),
                ('bool4', models.BooleanField(default=False)),
                ('bool5', models.BooleanField(default=False)),
                ('bool6', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Daily_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=5000)),
                ('order', models.IntegerField(default=1)),
                ('show', models.BooleanField(default=False)),
                ('char1', models.CharField(max_length=5000)),
                ('char2', models.CharField(max_length=5000)),
                ('char3', models.CharField(max_length=5000)),
                ('int1', models.IntegerField(default=1)),
                ('int2', models.IntegerField(default=0)),
                ('int3', models.IntegerField(default=0)),
                ('int4', models.IntegerField(default=0)),
                ('int5', models.IntegerField(default=0)),
                ('int6', models.IntegerField(default=0)),
                ('bool1', models.BooleanField(default=False)),
                ('bool2', models.BooleanField(default=False)),
                ('bool3', models.BooleanField(default=False)),
                ('bool4', models.BooleanField(default=False)),
                ('bool5', models.BooleanField(default=False)),
                ('bool6', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailys_1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
