# Generated by Django 4.1.4 on 2023-08-10 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_day_1_daily_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_1',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailys_1', to='api.day_1'),
        ),
    ]
