# Generated by Django 4.1.4 on 2023-08-18 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_daily_1_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailys', to='api.day'),
        ),
    ]
